name: actions-env-vars-secrets

on:
  workflow_dispatch:

jobs:
  job-staging:
    runs-on: ubuntu-slim
    environment: staging
    steps:
      - name: staging-step-1
        run: |
          echo "Staging Job"
          echo "Repo Variable: ${{ vars.REPO_VARIABLE }}"
          echo "Staging Variable: ${{ vars.EXAMPLE_VARIABLE }}"
          echo "Repo Secret: ${{ secrets.REPO_SECRET }}"
          echo "Staging Secret: ${{ secrets.EXAMPLE_SECRET }}"

  job-production:
    runs-on: ubuntu-slim
    environment: production
    steps:
      - name: production-step-1
        run: |
          echo "Production Job"
          echo "Repo Variable: ${{ vars.REPO_VARIABLE }}"
          echo "Staging Variable: ${{ vars.EXAMPLE_VARIABLE }}"
          echo "Repo Secret: ${{ secrets.REPO_SECRET }}"
          echo "Staging Secret: ${{ secrets.EXAMPLE_SECRET }}"
